### ISSUE TITLE
Not showing latest drivers for non-dch

### ISSUE THREAD

**Issue by Dantasstic** [ElPumpo/TinyNvidiaUpdateChecker#101]
The app doesn't seem to be working currently, as GFE shows there is a driver update, but the app claims my drivers are actually up to date.

Screenshot: https://i.imgur.com/CZMAb1i.png

**Comment by LuckyGray7** [comment]
Yupp completely busted for me as well, showing drivers are up to date when they are not.

**Comment by ElPumpo** [comment]
Sorry for the extreme delay everyone! I'm going to take a look into fixing that today 👀

**Comment by HGGamers** [comment]
I think there is an issue on their API or I don't know? Or did they change something?

It's because of the dtcid.

This will get the old version (dtcid= 0): 

https://www.nvidia.com/Download/processDriver.aspx?psid=107&pfid=877&osid=57&lid=9&dtcid=0&ctk=0

And this will get the new version (dtcid= 1):

https://www.nvidia.com/Download/processDriver.aspx?psid=107&pfid=877&osid=57&lid=9&dtcid=1&ctk=0

If I use the Driver Downloads (https://www.nvidia.com/download/index.aspx?lang=en-us#), it also appends dtcid=1:
processDriver.aspx?psid=107&pfid=877&rpf=1&osid=57&lid=9&lang=en-us&ctk=0&dtid=1&dtcid=1

But no idea what exactly is going on

**Comment by ElPumpo** [comment]
Damn you are correct! I recently reinstalled Windows and it came with DCH drivers. DTCID is set to `1` if you're using DCH drivers.

**Comment by fyr77** [comment]
This happens with my EnvyUpdate utility as well. I can only assume Nvidia is no longer supporting non-DCH drivers...

Using the Nvidia driver website leads to the same results, with Windows 7 (non-DCH) only getting older drivers.

I don't think this issue can be fixed on your (or my) part. The only thing one can do is to inform users of the apparent EOL of non-DCH drivers, I suppose.

**Comment by ElPumpo** [comment]
So okay a long time has passed by now. I know I'm very late on this, my understanding now is that NVIDIA have discontinued non-DCH drivers and only release DCH drivers.

They have also removed the selection of DCH/non-DCH in the regular "driver download site". I could swear this was the case, that you was able to choose DCH/non-DCH. Either way in https://www.nvidia.com/download/find.aspx you can still search for non-DCH drivers.... and apparently are dated to 472.12. This confirms it's discontinued.
![image](https://user-images.githubusercontent.com/12564301/175807787-63c23796-766a-46a9-a0f5-8b27beeb2bc2.png)

Installing a DCH driver on a currently non-DCH driver should not be an issue either. So the fix for now is to just always choose DCH.
