### ISSUE TITLE
Alternative to TinyNvidiaUpdateChecker

### ISSUE THREAD

**Issue by vojtasrb** [ElPumpo/TinyNvidiaUpdateChecker#107]
I have to say, it's such a shame that this isn't being updated to properly install newest drivers. It was very helpful to our firm with several computers. Thanks to this program, I have been able to quickly and remotely download & install the newest drivers. 

Does something similiar exist where I can update drivers via command line as well?

Thanks for any suggestions.

**Comment by mt025** [comment]
I was wondering why my graphics kept crashing, turns out I was using the wrong version. 

For anyone coming across this, the closest I have found is TechPowerUp's NVCleanstall ([https://www.techpowerup.com/download/techpowerup-nvcleanstall/](https://www.techpowerup.com/download/techpowerup-nvcleanstall/)) however this doesn't appear to support command line but allows a lot of configuration to which features you install.

**Comment by Technetium1** [comment]
What the actual hell are you two talking about?

**Comment by ElPumpo** [comment]
Closing as looking for alternatives is obviously not helping the issue, and there's already an open issue.
