### ISSUE TITLE
Add GeForce MX150

### ISSUE THREAD

**Issue by jobhax25** [ElPumpo/TinyNvidiaUpdateChecker#132]
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:

gpuName:    GeForce MX150
isNotebook: True

Error: `PS C:\Users\jobha\Downloads> .\TinyNvidiaUpdateChecker.v1.15.2.exe --debug
TinyNvidiaUpdateChecker v1.15.2

Arg: --debug

configFile: C:\Users\jobha\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Searching for Updates . . . OK!
offlineVer: 1.15.2
onlineVer:  1.15.2

Retrieving GPU information . . . ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:

gpuName:    GeForce MX150
isNotebook: True

Press any key to exit...`

**Comment by ZenitH-AT** [comment]
This should be fixed by https://github.com/ZenitH-AT/nvidia-data/commit/92eeb83f5f35909fd1b17ca7a40808882234a9dc.

I checked out the series name [here](https://www.nvidia.com/Download/API/lookupValueSearch.aspx?TypeID=2) and it seems Nvidia puts the MX150 under the "GeForce MX100 Series (Notebook)" series. After updating the notebook series name regex in my script, it solved the issue.

Most other laptop GPU series names have "(Notebooks)" in the name (e.g. "GeForce MX200 Series (Notebooks)"). Really weird they'd have this naming inconsistency in the same generation of GPUs.

**Comment by ElPumpo** [comment]
Nice. Thanks for your help!
