### ISSUE TITLE
Add option or toggle to check/download/install the NVIDIA Studio Driver 

### ISSUE THREAD

**Issue by gpshonik** [ElPumpo/TinyNvidiaUpdateChecker#137]
It would be great to have the option to specify the driver type Studio Driver (SD) vs the Game Ready Driver (GRD). Thanks for this tool!

**Comment by ElPumpo** [comment]
I don't belive the NVIDIA API used has a check for this.

**Comment by gpshonik** [comment]
Understood, please feel free to close.

**Comment by ZenitH-AT** [comment]
Might be possible since studio drivers can be found with the [Advanced Driver Search](https://www.nvidia.com/Download/Find.aspx).

[Example for 3070](https://www.nvidia.com/Download/processFind.aspx?pfid=933&osid=57&dtcid=1&lid=1). `dtcid` is for DCH and `lid` is for language.

The only thing is this is a web page, so scraping would be required, though maybe an API is available for this.

**Comment by ElPumpo** [comment]
Nooooo haha never going back to that old implementation I had a similar one before. As API does not support it neither wont I.🤝
