### ISSUE TITLE
Implement self updater

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/TinyNvidiaUpdateChecker#138]
Because doing it yourself in 2022 is silly

**Comment by yslupdates** [comment]
Thanks for adding it to your list!

**Comment by ElPumpo** [comment]
No worries👍

**Comment by rullingen** [comment]
Really hoping for this,

One of the great things about your tool is the severely reduced amount of interaction it requires in comparison to GFN and I'd hazard a guess that its the reason a lot of people are using it.

However updates seem to be fairly regular at the moment (good thing) but it currently requires visiting the releases page, downloading the new version, renaming it so that the shortcuts still work and then dropping it in my apps folder every time. This all detracts from the user friendliness of the interaction in a big way.

**Comment by ElPumpo** [comment]
Agreed @rullingen I will make it a priority

**Comment by rullingen** [comment]
Amazing, cheers mate.

**Comment by ElPumpo** [comment]
I have now renamed the exe files in all releases. They no longer contain the version number

**Comment by ElPumpo** [comment]
v1.19.0 anyone?
