### ISSUE TITLE
It's not tiny anymore

### ISSUE THREAD

**Issue by pravic** [ElPumpo/TinyNvidiaUpdateChecker#157]
Since https://github.com/ElPumpo/TinyNvidiaUpdateChecker/releases/tag/v1.16.0 :(

**Comment by ElPumpo** [comment]
Haha I know. Single file deplyoment for .NET 7 makes the file much bigger. But there's nothing I can do about it sadly

**Comment by Technetium1** [comment]
11MB is still quite tiny, especially compared to what it replaces.

**Comment by ElPumpo** [comment]
I'm not sure why it went up to 11 MB. The libraries I use aren't so big either lol. Could it be the WinForms compability libraries?

**Comment by Technetium1** [comment]
Maybe consider trying to publish a self-contained trimmed version? Seems the only way to update that runtime is with a new release, but that might not be a problem due to the self updater from #138

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained
https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

**Comment by ElPumpo** [comment]
![image](https://user-images.githubusercontent.com/12564301/215345620-c4168bb5-e114-4637-b369-da22d8328d43.png)

You can't do that for Windows Forms

**Comment by Technetium1** [comment]
Seem to have skipped over that bit :frowning:

**Comment by absidue** [comment]
As you've switched from dotnet framework to dotnet, you should be able to use the builtin JSON support instead of needing the extra library for it. That might slightly reduce the size of the binary.

**Comment by ElPumpo** [comment]
Last I checked the json library was about 300 kb or something

**Comment by ElPumpo** [comment]
So quick update there's not much I can do. Like what should I do, rename project to NvidiaUpdateChecker? Haha. Or perhaps move back to .NET Framework, or just close this issue hehe?

**Comment by pravic** [comment]
I guess, the renaming will be fair enough.

**Comment by absidue** [comment]
If you do go ahead with renaming the project, make sure to keep the name of this GitHub repo the same, otherwise you'll break the update check, for versions of the tool released before the rename.
relevant line of code: https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/cde51d7f25e1b6f78660e52a073e825698766db2/TinyNvidiaUpdateChecker/MainConsole.cs#L44

**Comment by pravic** [comment]
Not really. Github auto redirects to the new project location.

**Comment by ElPumpo** [comment]
I belive the auto redirect is 'only' active for one year or so then you're on your own. And it was a joke I'm not renaming the project lol.

Hearing people complain about 11 MB in 2023 just screams brokie. It's time to upgrade

**Comment by pravic** [comment]
> I believe the auto redirect is 'only' active for one year or so then you're on your own.

Again, not true: https://github.com/orgs/community/discussions/22669

**Comment by pravic** [comment]
> Hearing people complain about 11 MB in 2023 just screams brokie.

Nope, it's not about 11 MB. It's about **Tiny**NvidiaUpdateChecker - it used to be true but now it's a false advertisement. Not a big deal, but still a lie.

**Comment by ElPumpo** [comment]
I mean what is tiny nowadays anyway? The new Call of Duty game is like 200 GB geez. Think of it like inflation

**Comment by ElPumpo** [comment]
Jokes aside I have no clue as to why it is 11 MB. Since it still requires .NET 7 Runtime it's not framework independent. If I recall correctly that would bump TNUC to around 150 MB.

And I have not tested building a boilerplate project to see if there's something weird happening, because to me 11 MB is also really weird since it was 600 kb before.

Don't know if there's anything I can do about it.

**Comment by absidue** [comment]
My guess is that it's the WinForms libraries. In .Net Framework they were probably part of the runtime as it was Windows only, but as .Net is cross-platform now, they probably separated the WinForms libraries from the runtime install.

**Comment by ElPumpo** [comment]
@pravic okay the cake is a lie. What do you expect me to do?

**Comment by johngagefaulkner** [comment]
> @pravic okay the cake is a lie. What do you expect me to do?

WinForms won't be an issue when I finish rebuilding it in WinUI 3 + WinAppSDK. <sub>gonna be larger than 11MB tho</sub>

**Comment by pravic** [comment]
> @pravic okay the cake is a lie. What do you expect me to do?

Nothing :)

It's no big deal. I, personally, will stay with an older version - it works, so why bother.

**Comment by pravic** [comment]
@ElPumpo By the way, did you update your https://github.com/ElPumpo/TinyNvidiaUpdateChecker#dependencies section when switched away from WinForms?

**Comment by ElPumpo** [comment]
As you wish. I have not moved away from WinForms and it's not in my dependencie list.

Will be archiving the issue. Open issues for serious issues

**Comment by ElPumpo** [comment]
Lol this aged well
