### ISSUE TITLE
Remove WinRAR requirement for minimal installer

### ISSUE THREAD

**Issue by SirMarth01** [ElPumpo/TinyNvidiaUpdateChecker#16]
If WinRAR is required for its ability to create RAR archives, there's no existing alternative.

Otherwise, there are a few options:
- 7zip can extract RAR files, so searching for a 7zip installation instead of/in addition to WinRAR should work.
- RARLAB does offer [an unRAR DLL and source code](http://www.rarlab.com/rar_add.htm), but the license comes with some conditions that make it incompatible with the GNU GPL without making an exception [like 7zip did](http://7-zip.org/license.txt).
- There are a few other implementations of unRAR utilities available that claim to be LGPL reverse engineered, discussed [here](https://sourceforge.net/p/sevenzip/feature-requests/1229/?limit=25). [SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf/tree/master/ext/unarr) has the most modern version available, but no separately available DLL. [The Unarchiver](https://theunarchiver.com/command-line) has some outdated .exe versions available. (LGPL 2.1+ for that.)

EDIT: And now realizing that the problem might not be unRAR but SFX. Entirety of everything above might be useless.

**Comment by ElPumpo** [comment]
Correction: the drivers e.g `385.41-desktop-win10-64bit-international-whql.exe` are inside a 7zip SFX archive. I'll look into alternatives!

**Comment by SirMarth01** [comment]
The [7-Zip Extra](http://www.7-zip.org/download.html) download offers a command line executable and a DLL. Just pointing 7-Zip to the driver executable was enough to get 7-Zip to extract it on my system, even through the command line version. I can't speak as to how to go about implementing 7-Zip into your program, but it's probably the best way forward.

**Comment by ElPumpo** [comment]
> EDIT: And now realizing that the problem might not be unRAR but SFX. Entirety of everything above might be useless.

haha exactly, seems like I only have 1 choice:
- make 7zip compatiable (cuz it works aswell)
     - but would require it to be installed? i don't want to ship an extra libary
     - still gotta confirm some command line arguments

**Comment by SirMarth01** [comment]
On the one hand, 7-zip is pretty commonly used, I imagine especially among potential users of this program.

On the other hand, forcing the user to install a program that they have to obtain elsewhere to access a feature is also undesirable.

Proposal: offer both options? Ship two ZIP files, one with 7za.exe (7za.dll only handles 7z format; if you planned on using a .dll instead of an .exe, you'll need the regular 7z.dll.) and one without. (Include HTML Agility Pack in both, for convenience.)

**Comment by ElPumpo** [comment]
Ok but who doesn't have either winrar or 7zip on their computer? I even wanted to remove html agility pack because it made the application less portable.

**Comment by levicki** [comment]
@ElPumpo 
You should not assume that people have WinRAR and 7-Zip.

If you want to automatically extract the driver why not just use SevenZipSharp, and save both users and yourself the trouble?

https://sevenzipsharp.codeplex.com/

**Comment by ElPumpo** [comment]
> You should not assume that people have WinRAR and 7-Zip
well I do..

and as I've already said above, I really don't want to add more libaries that I ship with the application

**Comment by levicki** [comment]
You are free to do as you wish, but then you will have less people using your application, which defeats the purpose of making it available to everyone in the first place. WinRAR is not free software -- it is shareware, and shareware cannot be used for free past the initial trial period.

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.0 beta 1.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1297504/TinyNvidiaUpdateChecker.v1.9.0.beta.1.zip)
build with 7zip support!

**Comment by berserkwarwolf** [comment]
Thanks @ElPumpo for using the better AND open source alternative !

**Comment by Voxilli** [comment]
Thank you for the update. Unfortunately, I am receiving this error in regards to HtmlAgilityPack:

```
Attempting to download HtmlAgilityPack.dll . . . ERROR!
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at TinyNvidiaUpdateChecker.MainConsole.CheckDependencies()



Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'HtmlAgilityPack, Version=1.5.1.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The system cannot find the file specified.
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)
```

**Comment by ElPumpo** [comment]
**Note:** if the application crashes whilst trying to download htmlagilitypack it's because it isn't released yet on github, and the application assumes that it exists there. I've also updated to the new version of htmlagilitypack so you have to download it manually **Workaround:** download the latest version of htmlagilitypack [HtmlAgilityPack.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1298650/HtmlAgilityPack.zip)

**Comment by seagull** [comment]
Would you consider having a download for the 7ZipSharp library in case it is absent, like you do for HTMLAgilityPack? That way you only need to ship a single executable.

**Comment by MikeZeDev** [comment]
You can always ship 7ZipSharp and HtmlAgilityPack as binary resources and use them dynamically if you are so concerned about libraries. 

Or include their source in your own maybe? 

It would require more programming but i think its better than downloading them. I am not fan of program downloading libraries, people may argue that is a security problem. Any solution would be better than an already installed program

**Comment by ElPumpo** [comment]
You know what, I'll have look into shipping the app with the libaries then... But I'm not sure about the license... HAP is licensed under MIT so I think I can include it, 7zipsharp is under LGPL?

**Comment by levicki** [comment]
@ElPumpo 
Yes, under LGPL 3.0: http://www.gnu.org/licenses/lgpl.html

In short, to distribute SevenZipSharp you need to:

1. Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License.
2. Accompany the object code with a copy of the GNU GPL and this license document.

In any case, it is better to distribute both AgilityPack and SevenZipSharp because you control the version, new versions may break your program be it intentionally (API change) or unintentionally (bug).

**Comment by ElPumpo** [comment]
Ok @levicki thanks for the info!

**Comment by levicki** [comment]
@ElPumpo 
You are welcome.

**Comment by grynnan** [comment]
So I was just going to tell ElPumpo about 7-zip, and sevenzipsharp.. I think I don't have to. =P
Btw, codeplex is shuting down.. 7-zip extra is also available at sourceforge (Personal note: SF.. Eew!)

**Comment by ElPumpo** [comment]
Yea why did they not chose github?

**Comment by ElPumpo** [comment]
So after some research I'm left confused yet again

**Why did you recommend me SevenZipSharp?!**
- has not been updated since 2011
    - 'newest' fork by [StevenBonePgh](https://github.com/StevenBonePgh/SevenZipSharp) was updated ~1 year ago
- still requires 7zip installed (7zip binaries, `7z.dll` etc)
- **NO** documentation

I'm not ready to pack 5000 dll files into TNUC, sorry. Unless I find another solution to this, I guess will stay with what I'm already using... 

and I still want an answer for:
> who doesn't have either winrar or 7zip on their computer?

**Comment by seagull** [comment]
I have no problem with just including 7z.exe (and the DLLs) with the binary when I distribute it. Would that work? Will the program search its immediate directory for 7z (or if not, could it?)

**Comment by levicki** [comment]
@ElPumpo 
Yes, SevenZipSharp project is old and seems abandoned but it is the only fully functional wrapper around the COM interface from 7z.dll and its LZMA SDK. If you prefer writing your own from scratch be my guest.

As for what is needed for distribution the only thing you need besides SevenZipSharp.dll is 7z.dll which contains actual decompression code. The advantage of this approach is that you can do everything from your own application process.

You have another option and that would be to bundle 7za.exe with your application, then launch it as a process from your code and wait for it to finish, but unless you create pipes for STDIN and STDOUT to communicate with 7za.exe process (which still requires good Windows API knowledge and some marshalling) you won't be able to display the decompression progress, not to mention that launching console apps in a separate process when there is a programatic way of doing decompression is ugly.

It's your project anyway, so do as you wish. Hopefully you find my advice helpful.

**Comment by ElPumpo** [comment]
> You have another option and that would be to bundle 7za.exe with your application, then launch it as a process from your code and wait for it to finish, but unless you create pipes for STDIN and STDOUT to communicate with 7za.exe process (which still requires good Windows API knowledge and some marshalling) you won't be able to display the decompression progress, not to mention that launching console apps in a separate process when there is a programatic way of doing decompression is ugly.

have you tried out v1.9.0-beta1? it uses `7zG.exe` which will show a GUI whilst extracting the content, which is good enough i say.

>  You can argue that those 95% don't need your program, but I'd say that even those who have 7-Zip don't because they can find and download and extract the driver on their own

Sure thing man, but exactly which files should you extract; and which ones shouldn't you ? 🔢 

> For a program to be useful it has to offer a signiicant amount of convenience and this convenience will always be more significant to those who are not tech savvy already.

Then I'll say again that for the feature to be effective, the user **must fully uninstall the current drivers using DDU** and then use the extracted drivers that TNUC makes. This feature is only for advanced users, and I expect advanced users to have either 7Zip or WinRAR installed.

**Comment by grynnan** [comment]
So after some research I'm left confused yet again

Why did you recommend me SevenZipSharp?!

    has not been updated since 2011
        'newest' fork by StevenBonePgh was updated ~1 year ago
    still requires 7zip installed (7zip binaries, 7z.dll etc)
    NO documentation

**Old, yes, but it works. And the docu is good.**

I'm not ready to pack 5000 dll files into TNUC, sorry. Unless I find another solution to this, I guess will stay with what I'm already using...

__Ehm.. read the docu? =P
Nope, not 5000, nor 500 or 50.. more like 5.. or 15 if you want .FAR support (Who uses .far anyway?)__

and I still want an answer for:

    who doesn't have either winrar or 7zip on their computer?

__7zip, because a lot of people doesn't know about it.
Winrar, because they use the built in crap in windows.__

**Comment by ElPumpo** [comment]
I'm not going to argue any more about this either, as I've already said the requirement is optional, and only used for the optional feature called 'minimal install' and is only for advanced users.

> I have no problem with just including 7z.exe (and the DLLs) with the binary when I distribute it. Would that work? Will the program search its immediate directory for 7z (or if not, could it?)

How about the application if searches for a `7ip` directory in the same directory the executable is located in, so you can use 7Zip portable?

**Comment by seagull** [comment]
Works for me!

**Comment by pulse-wave** [comment]
@ElPumpo I'm glad you're taking in consideration to switch to 7zip way to go!
thanks!!

**Comment by pulse-wave** [comment]
Personally I never installed winrar being shareware, plus 7zip is far better at archiving than winrar so it's a win\win :), can't wait to see it implemented in a non beta version thanks!

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.0-beta 2.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1315805/TinyNvidiaUpdateChecker.v1.9.0-beta.2.zip)
- now also supports a portable version of 7zip, there must be a `7-Zip` directory in the same folder that the application is in

**Comment by MrJustMe** [comment]
Hi there
> Ok but who doesn't have either winrar or 7zip on their computer?.

I :)
I went to test the beta 2 but i stopped when the message for winrar came out, so i finally did not test the beta.
Anyway, i think the 7zip option commented before could be the best and for sure i will prefer if you bundle the dll and the config file in the same download.
If you finally take this way, how to do this?. Well, i have no idea since i'm not a coder but you have a good example in one of the following links:
[http://www.peazip.org/peaextractor-unace-unrar-unzip.html](url)
Portable versions of the software (direct downloads):
Windows All: [https://osdn.net/dl/peazip/peaextractor-portable-1.3.WINDOWS.zip](url)
Windows 64 bits: [https://osdn.net/dl/peazip/peaextractor-portable-1.3.WIN64.zip](url)

Just download one of the portable versions, and look inside the downloaded zip for the folder `7z`, That's the way!!. Perhaps you can use an exact copy of that directory with your config file simply adding another text file referring to the Peazip Project or even is not requiered thanks to the GNU LGPL license.
Have a good day!.

**Comment by ElPumpo** [comment]
@MrJustMe sure thing man! Adding support for PeaZip now!
