### ISSUE TITLE
No dialog for missing .NET runtime

### ISSUE THREAD

**Issue by AlphaDE** [ElPumpo/TinyNvidiaUpdateChecker#181]
Despite .NET runtime 7.0.5 is installed, the program in version 1.16.5 throws a 

```
Architecture: x86
App host version: 7.0.2
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=7.0.2
```

and terminates.

The above URL does not point to the Desktop runtime, nevertheless even installing it from

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.5-windows-x64-installer

did not solve the issue. This version needs to be installed:

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.5-windows-x86-installer

The error message show get corrected and the program should wait some few seconds to have a chance to see the issue.

**Comment by ElPumpo** [comment]
Hi haha I wish I wrote that shitty error message because I didn't. Sorry I cannot do anything about it. Microsoft messed up the error dialog completly imo.

And it says specifically x86 and not 64...

**Comment by ElPumpo** [comment]
I was wrong, and there is no documentation about this that I could found.

There is a dialog to install the .NET runtime, but there's a catch. It only works if it a "Windows Application" in Visual Studio settings. If set to "Console Application", like it is, then no dialog appear, only in terminal. So moving to "Windows App" would fix it right? Yes, but there's some minor adjustments required to make it all work, because it handles console code differently.

Which I have done, https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/b923dcabe33d54dccc36eced425332da59296b90

So from next update the .NET dialog will appear for those who don't have the runtime installed. Perhaps I might migrate to x64 too.

**Comment by ElPumpo** [comment]
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/28b05435-61d0-4de7-ac60-835a01f967e9)
