### ISSUE TITLE
Nanazip cannot be accessed error

### ISSUE THREAD

**Issue by laxu** [ElPumpo/TinyNvidiaUpdateChecker#228]
I tried using the minimal installer, but with Nanazip installed it would complain about not being able to access the app from the depths of C:\Program files\WindowsApps.

I  had to uninstall Nanazip and install 7zip for this to work

I think it would be best to add the option to the config file to choose what library to use so this sort of clash cannot happen.

**Comment by Technetium1** [comment]
Feels reasonable to prefer 7zip and only use Nanazip if there's not an alternative option. I was unaware that NanaZip was on the Microsoft Store, that method of distribution might be part of the problem.
- [NanaZip](https://apps.microsoft.com/detail/9n8g7tscl18r?hl=en-us&gl=US)
- [NanaZip Preview](https://apps.microsoft.com/detail/9nzl0lrp1bnl?hl=en-us&gl=US)

**Comment by ElPumpo** [comment]
Hi laxu. Since my Store installation has somehow corrupted I am unable to install NanaZip. I used a VM to test its existence of the CLI it exposes, but not to run the full TNUC code in it.

I will do some investigating, perhaps TNUC is doing something it doesnt have to do. We dont need to access its directory like we currently do, its just a global library code 

As for a fix for choosing library I dont think is needed as these bugs should be patched not much changes happen.

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.19.1 dev 1.zip](https://github.com/user-attachments/files/15951012/TinyNvidiaUpdateChecker.v1.19.1.dev.1.zip)

Okay guys try this build

**Comment by ElPumpo** [comment]
Okay fixed for v1.19.1
