### ISSUE TITLE
Laptop no longer detected

### ISSUE THREAD

**Issue by Technetium1** [ElPumpo/TinyNvidiaUpdateChecker#232]
I removed configuration and the issue persists.
Happy to provide more information.

```
TinyNvidiaUpdateChecker v1.19.1

Arg: --debug

configFile: C:\Users\User\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us
DRIVER_TYPE: grd

Verifying internet connection . . . OK!

Searching for Update . . . OK!
offlineVer: 1.19.1
onlineVer:  1.19.1

Retrieving GPU information . . . OK!
gpuId:       940
osId:        57
isDchDriver: True
downloadURL: https://us.download.nvidia.com/Windows/560.70/560.70-notebook-win10-win11-64bit-international-dch-whql.exe
pdfURL:      https://us.download.nvidia.com/Windows/560.70/560.70-win11-win10-release-notes.pdf
releaseDate: 7/16/2024
downloadFileSize:  695 MiB
OfflineGPUVersion: 555.99
OnlineGPUVersion:  560.70
There is a new GPU driver available to download!

Extracting drivers . . .
Error reading configuration file, attempting to repair key 'Minimal install components' . . .
```

**Comment by ElPumpo** [comment]
Hi Tech! I don't really understand your issue you are having. the Download URL is a notebook driver? What's actually wrong?

**Comment by Technetium1** [comment]
Starts the process normally: 

![image](https://github.com/user-attachments/assets/834bc70c-1a53-4185-bf2a-c11812200c31)

This part should not happen: 

![image](https://github.com/user-attachments/assets/b4ed8509-fa54-427a-a516-cd42b068120e)

**Comment by ElPumpo** [comment]
Tech I don't understand your problem. You have to tell me what's actually wrong.

**Comment by Technetium1** [comment]
Even if I choose the correct components, it never detects the laptop correctly on further runs. Previously, I could click `install now`, and be presented with the Nvidia installation wizard directly after. There was not `Error reading configuration file, attempting to repair key 'Minimal install components'` a few weeks ago.

**Comment by ElPumpo** [comment]
Okay I get it now, what you are saying is that the NVIDIA API is returning a desktop driver, as your screenshot shows gpuId 940 which is "GeForce RTX 3060 Laptop GPU", and a notebook GPU, TNUC is already aware of this.

I also get similar issues, for me I have a 3070 desktop and the API is returning a notebook driver, WTF NVIDIA? I believe they are messing with us for some agenda.

The "Minimal install components error" is because it's your first time with the dialog. It should only appear once, and when you choose them it should not appear again.

**Comment by Technetium1** [comment]
If I choose correctly, it _still_ gives the error and forces choosing. I am sure shouldn't see the component selection window in the first place, unless something changed in the last few weeks for laptops.

**Comment by ElPumpo** [comment]
You have still not shown a error of any kind. The components are saved once selected. Show me an actual error

**Comment by Technetium1** [comment]
Last time I chose components and waited for the next available update. What would you like me to do for reproduction? I can remove all Nvidia things with DDU and rerun to show it doesn't save settings and prompts continually. I am only able to run this on a friend's laptop remotely, as I no longer own Nvidia hardware. Please pardon the resulting delays.

**Comment by ElPumpo** [comment]
Nah no worries you're good Tech. Look, you are telling me there's some issue going on, but you still have not shown it in images, or described it in a way I can understand you.

This Gpu Id `940` is only available as notebook, TNUC would never search for desktop drivers for this card, because none exist. I don't understand you.

There's no error shown anywhere. There's no "forcing" of anything, you enabled minimal installer, if you don't want it, then disable it in config?

**Comment by ElPumpo** [comment]
@Technetium1 ?

**Comment by Technetium1** [comment]
@ElPumpo I would still like to resolve this, but need to find time in common to reconnect. This will not be forgotten about.

**Comment by Technetium1** [comment]
This still occurs after drivers have been wiped. I'm unsure how to further pursue this. We will be moving this machine to Windows 11 in the near future. Hopefully this issue won't be reproducable.
