### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by sysworx** [ElPumpo/TinyNvidiaUpdateChecker#37]
The app cant check for updates of it self anymore:

![error](https://user-images.githubusercontent.com/5045879/35766665-9a7f12b4-08dc-11e8-86a3-d11b9d253395.PNG)

**Comment by zymoticspade** [comment]
I have been getting the same error message for around a week now. I tried re-downloading the script as well as HTMLAgilityPack but still the same issue. At least I know I't not alone. A fix would be highly appreciated since this is such a handy tool! Thx

**Comment by gindulis** [comment]
I'm getting the same thing:

![image](https://user-images.githubusercontent.com/2493521/35851574-1b38dee8-0b31-11e8-9886-ec11fcbc1198.png)

**Comment by ElPumpo** [comment]
Yea me too, I'm unsure what's causing this but i'll get it working again . . .

**Comment by dragondaud** [comment]
Quick search online shows that some people have this issue because of not using the latest .Net version in their project, but it might be fixed by linking the latest HtmlAgilityPack, 1.6.16, released 6 days ago. The base URL in your code is http, not https, but the error is clearly related to SSL, specifically not being able to negotiate a usable cypher to communicate. Which means the cypher NVIDIA is using is not supported by your program, either because of the .Net version used or configuration of same.

**Comment by dragondaud** [comment]
I downloaded the source, and tried rebuilding with newer HtmlAgilityPack, and that did not help. I then retargeted the project to .Net4.6.1 and rebuilt. That fixes the problem. It was set to 4.5, and I did not test anything but the latest, but using the latest requires end-user to also have the latest installed.

**Comment by dragondaud** [comment]
I forked the project, created a pull request for the fix, and uploaded a new release 1.10.1 in my fork with the fix. I'm sure the owner will update his repository, but feel free to use my update in the meantime. Requires .NET Framework 4.6.1 to be installed (Windows 10 November 2015 Update includes this).
https://github.com/dragondaud/TinyNvidiaUpdateChecker/releases/tag/v1.10.1

**Comment by ElPumpo** [comment]
Yea @dragondaud fixed the issue with his recent PR, expect a build to be released shortly fixing the problem.

**Comment by ElPumpo** [comment]
v1.11.0 has been released which solves the issue
