### ISSUE TITLE
Submit to chocolatey

### ISSUE THREAD

**Issue by Entze** [ElPumpo/TinyNvidiaUpdateChecker#58]
Are there any ambitions adding the TinyNvidiaUpdateChecker to the chocolatey repositories?

It would make the self-updater (#56) less urgent.

**Comment by Dreckiger-Dan** [comment]
[scoop](https://scoop.sh) would also be great

**Comment by SyntaxErrol** [comment]
And [AppGet](https://appget.net/) :)

**Comment by Dreckiger-Dan** [comment]
fyi: [scoop extras](https://github.com/lukesampson/scoop-extras) now contains tinynvidiaupdatechecker

**Comment by ElPumpo** [comment]
Wait what, it does? I tried to add TNUC to scoop but I didn't fully understand the documentation it had.

**Comment by lucknaumann** [comment]
@SyntaxErrol AppGet isn't a viable option because of MS [WinGet](https://docs.microsoft.com/en-us/windows/package-manager/winget/) - here's the [Repo](https://github.com/microsoft/winget-cli). Service shut down notice: [AppGet Repo](https://github.com/appget/appget), [Blog: The Day AppGet Died](https://keivan.io/the-day-appget-died/), & an article on [The Register](https://medium.com/@keivan/the-day-appget-died-e9a5c96c8b22).

**Comment by ElPumpo** [comment]
So chocolatey then. no clue how to submit TNUC

**Comment by lucknaumann** [comment]
@ElPumpo The Chocolatey site has some simple [courses](https://chocolatey.org/courses) and [docs](https://chocolatey.org/docs) that should help and there are people there to help with any questions.

**Comment by SyntaxErrol** [comment]
> @SyntaxErrol AppGet isn't a viable option because of MS...

Wow, that happened exactly 1 week after my comment. Isn't this just the typical story? MS's lack of communication sounds infuriating but at least there's now something better than Chocolatey that actually has a chance.

**Comment by lucknaumann** [comment]
@SyntaxErrol Yeah, I'm looking forward to MS WinGet. I agree, what MS did is pretty crappy.

**Comment by ElPumpo** [comment]
What Microsoft was disgusting for sure, no doubt about that.

**Comment by ElPumpo** [comment]
Request denied it's already on scoop. I don't want to manage my repo elsewhere
