### ISSUE TITLE
Temporary download directory causing issues on partial downloads

### ISSUE THREAD

**Issue by TotalLag** [ElPumpo/TinyNvidiaUpdateChecker#61]
Requesting a similar functionality to --force-dl, but instead of downloading without version check, it will only download if an update is needed, in addition to overwriting the directory where it extracts drivers to.

Ran into a problem where integrity failed with a driver download and cleanup of %temp% was required before files downloaded again.

**Comment by fishzle** [comment]
If the integrity check fails, it could clean itself up.
Then a user would just run it again, and there wouldn't be another switch to maintain.

**Comment by TotalLag** [comment]
Yes, if it behaved this way then I agree, no extra switch needed :)

**Comment by ElPumpo** [comment]
Sorry for the extreme delay. Isn't this what `--confirm-dl`. I'll look into the %temp% directory used causing issues.

**Comment by ElPumpo** [comment]
This is a weird issue since it checks if an existing file exists, if it does not match the size of the supposed driver file then it is deleted before downloading.
But I am going to change the code a bit so when it downloads, it will save as a `.partial` file format. This makes it easier to see a failed download, and if TNUC sees it then it is to be deleted. Most browsers do similar stuff.

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/3640d2eebd892df85756a978172849977e756b98 Improved the situation a bit but the code definitly needs a lot of love & rewriting. Many exceptions are not properly handled.

**Comment by ElPumpo** [comment]
I've tested to replicate the issue you're having. After installation the file is cleaned up which is up for a debate if a dialog should pop up asking if you want to keep the driver files.

Worst case if it %temp%/<driver version> doesn't get cleaned up after installation then still at least the code now checks the driver file size, which shouldn't be incomplete anyways since it nows gets downloaded as a `.part` file until it's completed where it then gets renamed back and there's a file size check, too.

(The dialog file downloader does not have this new code.. yet)

I'll be closing this issue if it happens to you again then you'll have to reopen it.

![image](https://user-images.githubusercontent.com/12564301/175812314-7261004e-78d6-4f97-ad52-8d1520871af2.png)

This is what happens when there's existing files and minimal install is used, and quiet mode is on.
