### ISSUE TITLE
DCH drivers no longer supported

### ISSUE THREAD

**Issue by vegetka** [ElPumpo/TinyNvidiaUpdateChecker#99]
On laptop (Dell 7577) release v1.14.4: gives error: Your GPU uses DCH drivers which are not supported… 
Previous releases work well.

**Comment by fajrocha** [comment]
I am having the same issue on my desktop, with an RTX3060. Previous release also works fine.

**Comment by Priring** [comment]
Same issue here on GTX 970 desktop GPU. On previous release, I was able to update driver all the way up until now (471.68).

**Comment by ElPumpo** [comment]
I removed DCH driver support because my understanding is that they are supposed to be updated using Windows Update. But it seems like many use this tool 'anyway'.

If y'all really want I could add it back?

**Comment by ecarre** [comment]
I'm on a new install of Windows 10, it looks like windows update didn't give me the last version and your tool do.

On Nvidia website I found a [FAQ](https://nvidia.custhelp.com/app/answers/detail/a_id/4777/~/nvidia-dch%2Fstandard-display-drivers-for-windows-10-faq) where they say "When directly comparing the two driver types, the DCH driver package has a smaller size and a faster installation time than the Standard package."

You are recreating new packages from the nvidia's one so you're doing the same thing.

If windows update can handle the driver it can be cool, but i'm not sure it will be as fast as your tool. (thank you for your work by the way)

**Comment by fajrocha** [comment]
So, correct me if I am wrong, but now I have to install NVIDIA drivers through Windows Updater instead of this tool? If yes, it's a real bummer, I really like your tool. Have been using it for years, it's fast, clean and not invasive like say GeForce Experience which once, despite me specifically telling it to not mess my games' graphic settings, decided to "optimize" everything anyway.

I would prefer if you added DCH driver support back, unless it's somehow detrimental. Thank you for your work!

**Comment by ElPumpo** [comment]
Okay my understanding was wrong then, sorry. I assumed Windows Update kept it updated. I'll add it back and release an update.

**Comment by ElPumpo** [comment]
Okay new release, v1.14.5 is out with DCH driver support readded

**Comment by vegetka** [comment]
Thank you for that change.
